version: '3.8'

networks:
  corp:
    driver: bridge

services:
  ash:
    container_name: ash
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/ash/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: ash:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure
